-- MySQL Script generated by MySQL Workbench
-- Mon Jun  7 21:47:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema classicmodels
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dw_gama_academy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dw_gama_academy` ;

-- -----------------------------------------------------
-- Schema dw_gama_academy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dw_gama_academy` DEFAULT CHARACTER SET utf8mb4 ;
USE `dw_gama_academy` ;

-- -----------------------------------------------------
-- Table `dw_gama_academy`.`dim_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_gama_academy`.`dim_cliente` (
  `ID_Cliente` INT(11) NOT NULL AUTO_INCREMENT,
  `Cod_Cliente` INT(11) NULL DEFAULT NULL,
  `Nom_Cliente` VARCHAR(50) NULL DEFAULT NULL,
  `Nom_Cidade` VARCHAR(50) NULL DEFAULT NULL,
  `Nom_Estado` VARCHAR(50) NULL DEFAULT NULL,
  `Num_Cep` VARCHAR(15) NULL DEFAULT NULL,
  `Nom_Pais` VARCHAR(50) NULL DEFAULT NULL,
  `Val_Limite_Credito` DECIMAL(22,0) NULL DEFAULT NULL,
  `Dat_Inicio_Vigencia` DATETIME NULL DEFAULT NULL,
  `Dat_Fim_Vigencia` TINYTEXT NULL DEFAULT NULL,
  `Bol_Ativo` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 123
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dw_gama_academy`.`dim_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_gama_academy`.`dim_data` (
  `IDData` INT(11) NULL DEFAULT NULL,
  `DataCompleta` DATETIME NULL DEFAULT NULL,
  `Ano` INT(11) NULL DEFAULT NULL,
  `Mes` INT(11) NULL DEFAULT NULL,
  `Dia` INT(11) NULL DEFAULT NULL,
  `DiaSemana` INT(11) NULL DEFAULT NULL,
  `ID_Data` INT(11) NULL DEFAULT NULL,
  `DataAnoMesDia` TINYTEXT NULL DEFAULT NULL,
  `DataAnoMes` TINYTEXT NULL DEFAULT NULL,
  `Trimestre` INT(11) NULL DEFAULT NULL,
  `CodigoTrimestre` VARCHAR(2) NULL DEFAULT NULL,
  `NumeroSemana` INT(11) NULL DEFAULT NULL,
  `DiaNoAno` INT(11) NULL DEFAULT NULL,
  `DiaNaSemana` CHAR(1) NULL DEFAULT NULL,
  `NomeMes` VARCHAR(20) NULL DEFAULT NULL,
  `SiglaMes` VARCHAR(3) NULL DEFAULT NULL,
  `NomeDia` VARCHAR(20) NULL DEFAULT NULL,
  `SiglaDia` VARCHAR(3) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dw_gama_academy`.`dim_empregado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_gama_academy`.`dim_empregado` (
  `ID_Empregado` INT(11) NOT NULL AUTO_INCREMENT,
  `Cod_Empregado` INT(11) NULL DEFAULT NULL,
  `Nom_Empregado` VARCHAR(50) NULL DEFAULT NULL,
  `Des_Cargo` VARCHAR(50) NULL DEFAULT NULL,
  `Cod_Chefe_Empregado` INT(11) NULL,
  `Nom_Chefe_Empregado` VARCHAR(50) NULL,
  `Des_Cargo_Chefe` VARCHAR(50) NULL,
  `Dat_Inicio_Vigencia` DATETIME NULL DEFAULT NULL,
  `Dat_Fim_Vigencia` TINYTEXT NULL DEFAULT NULL,
  `Bol_Ativo` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Empregado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dw_gama_academy`.`dim_escritorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_gama_academy`.`dim_escritorio` (
  `Id_Escritorio` INT(11) NOT NULL AUTO_INCREMENT,
  `Cod_Escritorio` VARCHAR(10) NULL DEFAULT NULL,
  `Nom_Cidade` VARCHAR(50) NULL DEFAULT NULL,
  `Cod_Estado` VARCHAR(50) NULL DEFAULT NULL,
  `Nom_Pais` VARCHAR(50) NULL DEFAULT NULL,
  `Num_Cep` VARCHAR(15) NULL DEFAULT NULL,
  `Nom_Territorio` VARCHAR(10) NULL DEFAULT NULL,
  `Dat_Inicio_Vigencia` DATETIME NULL DEFAULT NULL,
  `Dat_Fim_Vigencia` TINYTEXT NULL DEFAULT NULL,
  `Bol_Ativo` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Escritorio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dw_gama_academy`.`dim_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_gama_academy`.`dim_produto` (
  `ID_Produto` INT(11) NOT NULL AUTO_INCREMENT,
  `Cod_Produto` VARCHAR(15) NULL DEFAULT NULL,
  `Nom_Produto` VARCHAR(70) NULL DEFAULT NULL,
  `Nom_LinhaProduto` VARCHAR(50) NULL DEFAULT NULL,
  `Num_EscalaProduto` VARCHAR(10) NULL DEFAULT NULL,
  `Nom_Distribuidor` VARCHAR(50) NULL DEFAULT NULL,
  `Dat_Inicio_Vigencia` DATETIME NULL DEFAULT NULL,
  `Data_Fim_Vigencia` TINYTEXT NULL DEFAULT NULL,
  `Bol_Ativo` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Produto`))
ENGINE = InnoDB
AUTO_INCREMENT = 111
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dw_gama_academy`.`fato_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_gama_academy`.`fato_vendas` (
  `SK_Dim_Produto` INT(11) NOT NULL,
  `SK_Dim_CLiente` INT(11) NOT NULL,
  `SK_Dim_Empregado` INT(11) NOT NULL,
  `SK_Dim_Escritorio` INT(11) NOT NULL,
  `SK_DIM_Data_Compra` INT(11) NOT NULL,
  `SK_DIM_Data_Pagamento` INT(11) NULL DEFAULT NULL,
  `SK_DIM_Data_Entrega` INT(11) NULL DEFAULT NULL,
  `COD_NumeroPedido` INT(11) NULL DEFAULT NULL,
  `QTD_ItemPedido` INT(11) NULL DEFAULT NULL,
  `QTD_Estoque` INT(11) NULL,
  `VLR_ItemPedido` DECIMAL(22,0) NULL DEFAULT NULL,
  `VLR_TotalItem` DECIMAL(32,0) NULL DEFAULT NULL,
  `VLR_VendaUnitario` DECIMAL(12,0) NULL,
  `VLR_SugestaoVenda` DECIMAL(12,0) NULL,
  `VLR_TotalNota` DECIMAL(32,0) NULL,
  `Dat_Inicio_Vigencia` DATETIME NOT NULL,
  CONSTRAINT `fk_fato_vendas_dim_produto`
    FOREIGN KEY (`SK_Dim_Produto`)
    REFERENCES `dw_gama_academy`.`dim_produto` (`ID_Produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_vendas_dim_escritorio1`
    FOREIGN KEY (`SK_Dim_Escritorio`)
    REFERENCES `dw_gama_academy`.`dim_escritorio` (`Id_Escritorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_vendas_dim_empregado1`
    FOREIGN KEY (`SK_Dim_Empregado`)
    REFERENCES `dw_gama_academy`.`dim_empregado` (`ID_Empregado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_vendas_dim_cliente1`
    FOREIGN KEY (`SK_Dim_CLiente`)
    REFERENCES `dw_gama_academy`.`dim_cliente` (`ID_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_vendas_dim_data1`
    FOREIGN KEY (`SK_DIM_Data_Pagamento`)
    REFERENCES `dw_gama_academy`.`dim_data` (`ID_Data`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_vendas_dim_data2`
    FOREIGN KEY (`SK_DIM_Data_Entrega`)
    REFERENCES `dw_gama_academy`.`dim_data` (`ID_Data`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_vendas_dim_data3`
    FOREIGN KEY (`SK_DIM_Data_Compra`)
    REFERENCES `dw_gama_academy`.`dim_data` (`ID_Data`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_fato_vendas_dim_produto_idx` ON `dw_gama_academy`.`fato_vendas` (`SK_Dim_Produto` ASC) VISIBLE;

CREATE INDEX `fk_fato_vendas_dim_escritorio1_idx` ON `dw_gama_academy`.`fato_vendas` (`SK_Dim_Escritorio` ASC) VISIBLE;

CREATE INDEX `fk_fato_vendas_dim_empregado1_idx` ON `dw_gama_academy`.`fato_vendas` (`SK_Dim_Empregado` ASC) VISIBLE;

CREATE INDEX `fk_fato_vendas_dim_cliente1_idx` ON `dw_gama_academy`.`fato_vendas` (`SK_Dim_CLiente` ASC) VISIBLE;

CREATE INDEX `fk_fato_vendas_dim_data1_idx` ON `dw_gama_academy`.`fato_vendas` (`SK_DIM_Data_Pagamento` ASC) VISIBLE;

CREATE INDEX `fk_fato_vendas_dim_data2_idx` ON `dw_gama_academy`.`fato_vendas` (`SK_DIM_Data_Entrega` ASC) VISIBLE;

CREATE INDEX `fk_fato_vendas_dim_data3_idx` ON `dw_gama_academy`.`fato_vendas` (`SK_DIM_Data_Compra` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
